# Generated by Django 2.1.4 on 2019-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
